export const studentDetail = {
    admissionDate: '',
    studentFirstName: '',
    studentClass: '',
    studentLastName: '',
    studentFatherName: '',
    studentMotherName: '',
    studentGender: '',
    studentDOB: '',
    studentCaste: '',
    studentSubCaste: '',
    studentReligion: '',
    studentNationality: '',
    studentMotherToungue: '',
    studentLangaugeKnown: '',
    studentBloodGroup: '',
    studentAadharNumber: '',
    studentEMINo: '',
    studentPreviousSchool: '',
    studentDiscount: '',
}
