export const studentDetail = {
    admissionNo:'0',
    admissionDate: new Date(),
    studentFirstName: '',
    studentClass: '',
    studentCommunity: '',
    studentLastName: '',
    studentFatherName: '',
    studentMotherName: '',
    studentGender: '',
    studentDOB: new Date(),
    studentCaste: '',
    studentSubCaste: '',
    studentReligion: '',
    studentNationality: '',
    studentMotherToungue: '',
    studentLangaugeKnown: '',
    studentBloodGroup: '',
    studentAadharNumber: '',
    studentEMINo: '0',
    studentPreviousSchool: '',
    studentDiscount: '0',
}
