export const studentDetail = {
    admissionId:0,
    admissionDate: new Date(),
    studentFirstName: '',
    studentClass: '',
    studentCommunity: '',
    studentLastName: '',
    studentFatherName: '',
    studentMotherName: '',
    studentGender: '',
    studentDOB: new Date(),
    studentCaste: '',
    studentSubCaste: '',
    studentReligion: '',
    studentNationality: '',
    studentMotherToungue: '',
    studentLangaugeKnown: '',
    studentBloodGroup: '',
    studentAadharNumber: 0,
    studentEMINo: 0,
    studentPreviousSchool: '',
    studentDiscount: 0,
}
